[tox]
envlist = py312, quality, docs
requires = tox-uv>=1

[pycodestyle]
max-line-length = 120

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pylint repo_tools_data_schema
    pycodestyle repo_tools_data_schema
    isort --check-only --diff repo_tools_data_schema

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest --cov=repo_tools_data_schema --cov-report=xml {posargs}

[testenv:docs]
runner = uv-venv-lock-runner
basepython = python3.12
dependency_groups = doc
allowlist_externals = make
changedir = {toxinidir}/docs
commands =
    make html
